### ISSUE TITLE
[HDI] Client timeouts on compression

### ISSUE THREAD

**Issue by thomasjungblut** [hdinsight/hbase-sdk-for-net#16]
Take the HBaseClientTests and add a compression to the schema:

    _testTableSchema.columns.Add(new ColumnSchema { name = "d", compression = "XXX"});

If you provide "GZ" it works fine, if you provide anything else (e.g. "SNAPPY", although Snappy is installed and actually works on the cluster) it will just timeout.
I guess the problem is on the server side and it hangs somewhere on verifying the compression algorithm somehow (which should just be a config lookup).

Cluster version: 3.1.1.406

We should send an appropriate error message and don't timeout here.

**Comment by thomasjungblut** [comment]
@duoxu I know you fixed the snappy installation back then, do we have any idea why it timed out when configuring something badly? Might also be fixed by hbase/stargate in the meantime...

**Comment by duoxu** [comment]
@thomasjungblut is this still an issue in 3.2, 3.3? I will test and figure it out.

**Comment by duoxu** [comment]
@thomasjungblut I am able to create table with compression = "SNAPPY" on newly created 3.3 clusters.

**Comment by thomasjungblut** [comment]
Thanks Duo, I know we are using Snappy ;) It was timing out on an compression algorithm that doesn't exist. E.g. Compression = "ololxyz".

**Comment by duoxu** [comment]
@thomasjungblut So this is a client issue using the wrong compression name? Could we close this issue as SNAPPY works in our SDK.

**Comment by thomasjungblut** [comment]
I'm not sure where the issue is, that's why there is a ticket :)

**Comment by duoxu** [comment]
@thomasjungblut At least for now SNAPPY seems working. Do you have repro for this issue? If not we can close it and create a new one when you hit this.

**Comment by thomasjungblut** [comment]
close :+1:
