### ISSUE TITLE
Support Alternatives to /hbaserest or /hbaserest0 RestEndpointBase

### ISSUE THREAD

**Issue by ryandanthony** [hdinsight/hbase-sdk-for-net#24]
Allow for using an alternative to  /hbaserest or /hbaserest0 RestEndpointBase. Not all deployments of HBASE REST will use /hbaserest or /hbaserest0.

**Comment by jking777** [comment]
Seconded.

**Comment by alenny** [comment]
Supported! 
I found HBase 1.0 deployed on Ubuntu does not use /hbaserest or /hbaserest0 as the base endpoint.
I read your code. Could you please expose alternativeEndpointBase in the HBaseClient class?
Thank you!

**Comment by ryandanthony** [comment]
I did a little more research on this and there is a way to do it without code changes, but it's definitely not pretty (i.e. my hope is to do a pull request to make it easier and less config file dependent). Doing it this way will set it up to do round robin across multiple nodes. 

In your app.conf add the following:
```xml
  <appSettings>
    <add key="WorkerHostNamePrefix" value="workernode"/>
    <add key="WorkerRestEndpointPort" value="20550"/>
  </appSettings>
```
Now in your C:\Windows\System32\drivers\etc\hosts file, add one or more IP addresses:
```text
10.1.1.90 workernode0 
10.1.1.91 workernode1
10.1.1.92 workernode2
```
And then create your client (where 3 is equal to the number of nodes):
```C#
var client = new HBaseClient(3);
```
