### ISSUE TITLE
Expose connection timeout

### ISSUE THREAD

**Issue by pawelpabich** [hdinsight/hbase-sdk-for-net#28]
Hi,

We had a problem with HBase cluster https://social.msdn.microsoft.com/Forums/en-US/c6bd04e9-e69b-4e96-b2ef-fa8abcf3bbc3/502-error-in-hbase-cluster?forum=hdinsight and it would take minutes for the client to time out. We would love to reduce the amount of time we need to wait before we know something is wrong.

Thanks

Pawel

**Comment by thomasjungblut** [comment]
+1
