### ISSUE TITLE
Idea: expose Async API only

### ISSUE THREAD

**Issue by pawelpabich** [hdinsight/hbase-sdk-for-net#32]
Why? The sync API simply calls .Result on the async API which will cause deadlocks in environments like WPF or MVC. This is a trap that confuses many people.

**Comment by duoxu** [comment]
@pawelpabich I am planning to do that.

@thomasjungblut What do you think? Since sync API simply calls .Result or .Wait. I looked at some other SDKs like cassandra-sharp, it seems exposing async APIs only.

**Comment by thomasjungblut** [comment]
@duoxu definitely a very good idea, a lot of confused people and inconsistency comes from that. 

We should consider bumping the next release to a major release so we can justify the api breaking change.

**Comment by duoxu** [comment]
@thomasjungblut 
OK. I will send another PR for this then. We are planning to release a new version of SDK soon, basically including all the changes recently. I will add release notes on Nuget webpage to document all the recent changes, hopefully people will notice that.

**Comment by duoxu** [comment]
Removed all sync APIs and will publish a new nuget package soon.
