### ISSUE TITLE
Implement DefaultRetryPolicy

### ISSUE THREAD

**Issue by pawelpabich** [hdinsight/hbase-sdk-for-net#36]
At the moment the code is commented out.

**Comment by thomasjungblut** [comment]
Instead of doing our down retry stuff I would like to leverage "The Transient Fault Handling Application Block" which is also used by Azure.

https://msdn.microsoft.com/en-us/library/hh680934%28v=pandp.50%29.aspx?f=255&MSPPError=-2147217396

**Comment by pawelpabich** [comment]
Another options is https://github.com/michael-wolfenden/Polly, which is very nice and works great.
