### ISSUE TITLE
Deadlock in WebRequesterBasic

### ISSUE THREAD

**Issue by anirudhsanthiar** [hdinsight/hbase-sdk-for-net#46]
In the WebRequesterBasic class, we have the following method:

    public HttpWebResponse IssueWebRequest(string endpoint, string method = "GET", Stream input =   null)
    {
       var response =  IssueWebRequestAsync(endpoint, method, input).Result;
       return response;
    }

A GUI client (such as a Windows Forms app) or an MVC client will deadlock if it calls the method as follows:
    `var requester = new Microsoft.HBase.Client.WebRequesterBasic();
    requester.IssueWebRequest("https://github.com/hdinsight/hbase-sdk-for-net");`

Mixing synchronous and asynchronous waiting is dangerous, see, for example http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

There are instances of synchronous blocking in `WebRequesterSecure` and `WebRequester` as well.
A possible fix would be to configure the awaits `IssueWebRequestAsync` to not capture the current `SynchronizationContext` using `ConfigureAwait(false)`

**Comment by duoxu** [comment]
Do the following options work for you?

1.override the SynchronizationContext

var sc = new SynchronizationContext();
SynchronizationContext.SetSynchronizationContext(sc);
{
  Invoke SDK commands here
}
2. Start an Async task
Task.Run(async () =>
           {
             Invoke SDK commands here
           });

**Comment by anirudhsanthiar** [comment]
The latter would work, but are there objects with thread affinity that are accessed by `IssueWebRequestAsync` ?

**Comment by anirudhsanthiar** [comment]
Could you either add a warning to the documentation asking users to not call methods like `IssueWebRequest` from a GUI context, or perhaps configure the await statements in the library to not capture context via ConfigureAwait(false) [see, for example, the section under "avoiding context" in [1](http://blog.stephencleary.com/2012/02/async-and-await.html)]

**Comment by duoxu** [comment]
@anirudhsanthiar We are planning to expose async APIs only, so that it will not confuse people any more.
