### ISSUE TITLE
Support stateless scanners

### ISSUE THREAD

**Issue by thomasjungblut** [hdinsight/hbase-sdk-for-net#47]
For VNet clusters and dedicated gateways, it is much nicer to use stateless scanners:

https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/rest/package-summary.html#operation_stateless_scanner

**Comment by thomasjungblut** [comment]
@maxluk maxim, do you know if that feature is working through the normal clusters (non vnet)?
It seems like neither /hbaserest/ nor /hbaserest0/ nor the plain / works through the IIS gateways.

**Comment by thomasjungblut** [comment]
Also I'm running into issues with `response.WebResponse.GetResponseStream()` returning a stream that protobuf apparently cannot read:

```
System.AggregateException: One or more errors occurred. ---> ProtoBuf.ProtoException: Invalid field in source data: 0
    at ProtoBuf.ProtoReader.ReadFieldHeader() in c:\Dev\protobuf-net\protobuf-net\ProtoReader.cs: line 666
   at proto_8(Object, ProtoReader)
   at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Read(Object value, ProtoReader source) in c:\Dev\protobuf-net\protobuf-net\Serializers\CompiledSerializer.cs: line 57
   at ProtoBuf.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source) in c:\Dev\protobuf-net\protobuf-net\Meta\RuntimeTypeModel.cs: line 775
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs: line 700
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs: line 588
   at ProtoBuf.Serializer.Deserialize(Stream source) in c:\Dev\protobuf-net\protobuf-net\Serializer.cs: line 77
   at Microsoft.HBase.Client.HBaseClient.<GetRequestAndDeserializeAsync>d__7f`1.MoveNext() in HBaseClient.cs: line 680
```

copying the response into a `MemoryStream` works, but doesn't deserialize the result (empty vs. 3 rows). I'm puzzled, it works fine from Java.

TODO: figure out what protobuf-net is doing wrong x.x

**Comment by duoxu** [comment]
@thomasjungblut stateless scanner currently is not supported throught HDInsight gateways. Because HDI gateways use IIS and ASP.NET, "<,>,*,%,&,:,\\,?" are not allowed in the urls.

So stateless scanner works inside vnet or you can deploy your own nginx gateways as a workaround.

I am not sure about protobuf thing. Maybe we need to regenerate a new protobuf? stateless scanner is introduced in 0.98.0.

**Comment by BryanHall** [comment]
@thomasjungblut have you had any luck getting this working inside the vnet? I would like to specify a subset of columns for my scan and that is supported in the stateless scanner, but does not appear to be in the normal scanner (through hbase_rest).

**Comment by thomasjungblut** [comment]
I'm pretty sure the code works, if protobuf wouldn't be such a pain. If you look into my forked repo you can see that the subset column feature is in there for stateless scanners.
I'm doing this in my private time, so I can't really tell you when I completely finish this work.

**Comment by thomasjungblut** [comment]
No clue what's wrong with the protobuf stuff. I tried the whole morning to get it to work- updated the schemas, tried with different versions of protobuf.net. All to no avail. 

Any pointers?

You can find my current state in, just in case someone has a good idea and wants to try it out:
https://github.com/thomasjungblut/hbase-sdk-for-net

**Comment by duoxu** [comment]
@thomasjungblut I also got exceptions. I used fiddler and found REST server actually returned something. In JSON it looks good. However in Protobuf, the CellSet model could not deserialize it. The stateless scanner and stateful scanner returned Protobuf raw messages looked similar though.

**Comment by thomasjungblut** [comment]
@duoxu yeah very weird. It is not a CellSet, not sure where the inconsistency comes from. I also tried IEnumerable/List of Cell, but that didn't help. Protobuf-net seems to do some magic around lists and iterators using length prefixes, not sure that is compatible with Java in that case. 

Not sure if we can find some protobuf descriptors in the rest server's jar, at least we could figure out if it is some inconsistency in the schema or just in the list handling.

**Comment by duoxu** [comment]
@thomasjungblut I just figured it out through reading the source code and test code of HBase. I am able to parse the returned stream. I will send a PR soon.

**Comment by thomasjungblut** [comment]
@duoxu good work. Can you please sketch the protocol here? I'll open a jira on hbase and create a documentation patch afterwards

**Comment by duoxu** [comment]
Sent a PR.
