### ISSUE TITLE
CreateScannerAsync and ScannerGetNextAsync called on differents hosts

### ISSUE THREAD

**Issue by BryanHall** [hdinsight/hbase-sdk-for-net#49]
When using a VNet and multiple region servers, the calls to CreateScannerAsync and ScannerGetNextAsync are not guaranteed to be sent to the same region server. This is a problem for a scanner because the scanner id information is local to that server. This results in a 404 error from the ScannerGetNextAsync call.

As a work around for this issue I added a "ScannerHost" field to the RequestOptions structure that is passed down with the call. I populate it after the CreateScannerAsync call with the value from the load balancer.

    RequestOptions options = RequestOptions.GetDefaultOptions();
    scannerInfo = await _hbaseClient.CreateScannerAsync(_tablename, scanSettings, options);
    options.ScannerHost = scannerInfo.Location.Host;
    _hbaseClient.ScannerGetNextAsync(scannerInfo, options)

I then use this in IssueWebRequestAsync as follows. This allows me to specify the host for the ScannerGetNextAsync and DeleteScannerAsync but leave other calls untouched.

    string host = balancedEndpoint.Host;
    if (options.ScannerHost != null)
        host = options.ScannerHost;

    UriBuilder builder = new UriBuilder(
        balancedEndpoint.Scheme,
        host,
        options.Port,
        options.AlternativeEndpoint + endpoint);

There is probably a cleaner way to set this up, but I wanted to provide the work around for reference.

**Comment by thomasjungblut** [comment]
Thanks for the feedback Bryan. 
I think it is a good idea, let's just rename "ScannerHost" to something like `AlternativeHost` to be consistent with the other properties.

**Comment by BryanHall** [comment]
Sounds good. Do you want me to put a pull request in?

*Bryan Hall* | Co-Founder, CTO | 619.977.5316
Email Copilot <http://emailcopilot.com/> - previously Embarke
Your revenue depends on email.  Make sure it gets to the inbox.

**Comment by thomasjungblut** [comment]
sure, bring it up!
