### ISSUE TITLE
Client library should be able to load balance across the set of rest endpoints in the cluster

### ISSUE THREAD

**Issue by ashitgosalia** [hdinsight/hbase-sdk-for-net#6]

**Comment by pawelpabich** [comment]
Hi,

I noticed that both https://c.azurehdinsight.net/hbaserest/version/cluster and https://c.azurehdinsight.net/hbaserest0/version/cluster work but this does not work when I create a stateful scanner. Is it because the scanner can be only accessed from the node where it was created ?

**Comment by pawelpabich** [comment]
CreateScanner and GetScannerNext always are sent to hbasereset01 which limits overall throughput of the cluster.
