### ISSUE TITLE
Does this client work with generic Apache HBase?

### ISSUE THREAD

**Issue by ghost** [hdinsight/hbase-sdk-for-net#68]
Has there anything been done to the HBase on the server side for this to be workable? How different is HDInsight HBase from Apache HBase? thanks

**Comment by duoxu** [comment]
@jesaremi  

VNET mode works for non HDInsight HBase clusters. Please refer to https://github.com/hdinsight/hbase-sdk-for-net/blob/master/Microsoft.HBase.Client.Tests/Clients/VNetClientTest.cs  how to specify the REST server ips when initialize the HBaseClient.

HDInsight clusters have SSL gateways in front so gateway mode only applies to HDInsight clusters. VNET mode skips the gateway and directly hits REST servers so it will work on Apache HBase also.
