### ISSUE TITLE
Support stateless scanners

### ISSUE THREAD

**Issue by ashitgosalia** [hdinsight/hbase-sdk-for-net#7]

**Comment by pawelpabich** [comment]
This should be available in HBase 0.98 which is what current version of HDInsight uses https://issues.apache.org/jira/browse/HBASE-9343.  But when I try to access https://mycluster.azurehdinsight.net/hbaserest0/pawel-hbase-testing-2/*?limit=1 (as per https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/rest/package-summary.html#operation_cell_query_multiple) I get the following error. It looks like the Windows Routing module does not like the new syntax. 

![image](https://cloud.githubusercontent.com/assets/347637/9322287/91305aee-45b4-11e5-9573-372740100b37.png)

**Comment by pawelpabich** [comment]
Another nice side effect of this new feature is that it lets us set the limit at the row level not cell level which is very handy.

**Comment by thomasjungblut** [comment]
carry on in #47

**Comment by BryanHall** [comment]
Thanks Thomas!
